env:
  global:
    - secure: RfSTgywOhS7ohmTTLGyqaC2RCD+Mx0aylrO2qCYU/0UQMpdGXnG0SakXYeqEe+L0RWqPFQoQ68jdYLYat//RyWTwyVVKciTJif+Cu7cFN03fQtds69A5sy5anH0MTy3tzTh4Ldtm61UDoCXK5aFyseYH9Gv65wQk+BYsaYKRs7c=
    - secure: TML4+pujHxptuY3ekyf7pNdFEMTEDRoqeJhAAjSFwxCpzgME84A+Efb3nyXm/3Ue5jkmuxLxRoyGbja4lb78i94ObD/g2dUn/Qm92APCChCvc07tps0mWZrET1EoXFHo1QCzzm97MjTv/cD1F1ROw/ZEbFDaTTKQDqNAuftdYn4=
    - secure: bTh6ycm70aLQlgGctT3nibnlSHlAO7gSYxX+5FX/mota6/0JgORXAXUgc/tbZr3HbFga6oDJ/axyRev6jZilhiKH+vGNQNzhfWbsHtzOKEW5IBeJgytHyi4o9/twwNrmCvBPWm6grFqKEjtqQKcSKyz73tl7P/cgBDLywSEpAA8=

branches:
  only:
    - master
  
notifications:
  email: false
  
language: cpp
 
compiler:
   - gcc
 
before_install:
  - git config --global user.email "${GH_MAIL}"
  - git config --global user.name "${GH_USER}"
  - ./.travis-Projektrapport.sh
  
script:
   - echo "Done"