/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Opamp_1.h>
#include <ProbeSignal.h>
#include <ProbeSignal_aliases.h>
#include <ADC.h>
#include <ProbeGND.h>
#include <ProbeGND_aliases.h>
#include <CALI.h>
#include <CALI_aliases.h>
#include <RED_LED.h>
#include <RED_LED_aliases.h>
#include <GREEN_LED.h>
#include <GREEN_LED_aliases.h>
#include <Clock_1.h>
#include <Calibrate.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

