CXX=arm-angstrom-linux-gnueabi-g++
SOURCES=main.cpp Kar.cpp KarContainer.cpp Message.cpp MessageQueue.cpp Thread.cpp Bridge.cpp SocketServer.cpp SocketClient.cpp KarBus.cpp
OBJECTS=$(SOURCES:.cpp=.o)
DEPS=$(SOURCES:.cpp=.d)
EXE=FlexPMS.devkit
CXXFLAGS=-I.

$(EXE):$(DEPS) $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJECTS) -L/usr/lib -L./lib -lpthread -lmysqlcppconn

%.d:%.cpp
	$(CXX) -MT$(@:.d=.o) -MM $(CXXFLAGS) $^ > $@

clean:
	rm $(OBJECTS) $(EXE) *.d *.o

-include $(DEPS)